version: '3'

services:
  mariadb:
    image: perriea/alpine-mysql:3.7
    hostname: mariadb
    environment:
      # CHANGEME MYSQL_ROOT_PASSWORD: root password
      - MYSQL_ROOT_PASSWORD="XXXXXXXXXXXXXXXXXXX"
      - MYSQL_USER="drone"
      # CHANGEME MYSQL_PASSWORD: drone password
      - MYSQL_PASSWORD="XXXXXXXXXXXXXXXXXXX"
      - MYSQL_DATABASE="drone"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
        window: 120s
      resources:
        limits:
          cpus: '40.000'
          memory: 1024M
    volumes:
      # WARNING: Linux case
      - /var/lib/mysql:/var/lib/mysql/
    networks:
      - private-database

  drone-server:
    image: drone/drone:0.8
    hostname: drone-server
    depends_on:
      - mariadb
    environment:
      # WARNING: disable in production
      - DRONE_DEBUG=true
      # CHANGEME: Randomly generate something at least 24 characters long with
      # a password generator.
      - DRONE_SECRET="CHANGEME"
      - DRONE_ORGS=""
      - DRONE_ADMIN="perriea"
      - DRONE_ADMIN_ALL="false"
      - DRONE_DATABASE_DRIVER="mysql"
      # CHANGEME: same string (user drone password)
      - DRONE_DATABASE_DATASOURCE="drone:XXXXXXXXXXXXXXXXXXX@tcp(mariadb:3306)/drone?parseTime=true"
      - DRONE_OPEN=false
      # CHANGEME: OPTIONAL DRONE_HOST
      - DRONE_HOST="http://drone.mycompany.com"
      # CHANGEME: generate Github token
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT="CHANGEME"
      - DRONE_GITHUB_SECRET="CHANGEME"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
        window: 120s
      resources:
        limits:
          cpus: '40.000'
          memory: 768M
    volumes:
      # WARNING: Linux case
      - /var/lib/drone:/var/lib/drone/
    networks:
      - public
      - private-database
    ports:
      - 80:8000

  drone-agent:
    image: drone/agent:0.8
    hostname: drone-agent
    command: agent
    depends_on:
      - drone-server
    environment:
      - DRONE_SERVER="drone-server:9000"
      # CHANGEME: same string (drone-server)
      - DRONE_SECRET="CHANGEME"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - public
      - private-agent

networks:
  public:
    driver: bridge
  private-agent: {}
  private-database: {}